import mongoose from 'mongoose';
/**
 * Image Schema for AI Gallery
 * Stores information about uploaded images including metadata and moderation status
 */
const imageSchema = new mongoose.Schema(
  {
    // User identifier (stored as Clerk user ID)
    userId: {
      type: String,
      required: true,
      index: true,
    },

    // Image metadata
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },

    description: {
      type: String,
      trim: true,
      maxlength: 500,
      default: '',
    },

    // Tags for searchability
    tags: {
      type: [String],
      default: [],
      index: true,
    },

    // Image category
    category: {
      type: String,
      enum: ['abstract', 'landscape', 'portrait', 'still-life', 'digital-art', 'photography', 'other'],
      default: 'digital-art',
      index: true,
    },

    // Cloudinary storage
    imageUrl: {
      type: String,
      required: true,
    },

    cloudinaryId: {
      type: String,
      required: true,
      unique: true,
    },

    // Thumbnail URL (auto-generated by Cloudinary)
    thumbnailUrl: {
      type: String,
      default: '',
    },

    // SEO-friendly slug
    slug: {
      type: String,
      index: true,
    },

    // Content classification
    isAdultContent: {
      type: Boolean,
      default: false,
    },

    // File information
    fileSize: {
      type: Number, // in bytes
      required: true,
    },

    mimeType: {
      type: String,
      enum: ['image/jpeg', 'image/png', 'image/webp'],
      required: true,
    },

    // Original filename
    originalName: {
      type: String,
      default: '',
    },

    // AI Moderation Status
    moderationStatus: {
      type: String,
      enum: ['Pending', 'Approved', 'Rejected', 'ManualReview'],
      default: 'Pending',
      index: true,
    },

    // AI Moderation Details - stores the response from OpenAI API
    moderationDetails: {
      categories: {
        hate: { type: Boolean, default: false },
        'hate/threatening': { type: Boolean, default: false },
        harassment: { type: Boolean, default: false },
        'harassment/threatening': { type: Boolean, default: false },
        'self-harm': { type: Boolean, default: false },
        'self-harm/intent': { type: Boolean, default: false },
        'self-harm/instructions': { type: Boolean, default: false },
        sexual: { type: Boolean, default: false },
        'sexual/minors': { type: Boolean, default: false },
        violence: { type: Boolean, default: false },
        'violence/graphic': { type: Boolean, default: false },
      },
      scores: {
        hate: { type: Number, default: 0 },
        'hate/threatening': { type: Number, default: 0 },
        harassment: { type: Number, default: 0 },
        'harassment/threatening': { type: Number, default: 0 },
        'self-harm': { type: Number, default: 0 },
        'self-harm/intent': { type: Number, default: 0 },
        'self-harm/instructions': { type: Number, default: 0 },
        sexual: { type: Number, default: 0 },
        'sexual/minors': { type: Number, default: 0 },
        violence: { type: Number, default: 0 },
        'violence/graphic': { type: Number, default: 0 },
      },
      flaggedReason: {
        type: String,
        default: '',
      },
      moderatedAt: Date,
    },

    // Community engagement
    likes: {
      type: Number,
      default: 0,
      min: 0,
    },

    likedBy: {
      type: [String],
      default: [],
    },

    views: {
      type: Number,
      default: 0,
      min: 0,
    },

    comments: {
      type: [
        {
          userId: String,
          username: String,
          text: String,
          createdAt: {
            type: Date,
            default: Date.now,
          },
        },
      ],
      default: [],
    },

    // Admin notes
    adminNotes: {
      type: String,
      default: '',
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt automatically
    indexes: [
      { userId: 1, createdAt: -1 }, // For finding user's images
      { moderationStatus: 1, createdAt: -1 }, // For admin moderation queue
      { tags: 1 }, // For tag searches
    ],
  }
);

// Index for text search on title and description
imageSchema.index({ title: 'text', description: 'text' });

// Pre-save hook to auto-generate thumbnail URL from Cloudinary ID
imageSchema.pre('save', function (next) {
  if (this.cloudinaryId && !this.thumbnailUrl) {
    // Using Cloudinary's transformation API for thumbnails
    this.thumbnailUrl = `https://res.cloudinary.com/${process.env.CLOUDINARY_CLOUD_NAME}/image/fetch/w_300,h_300,c_fill/v1/${this.cloudinaryId}`;
  }
  next();
});

// Method to get public image URL
imageSchema.methods.getImageUrl = function () {
  return this.imageUrl;
};

// Method to check if image has been approved
imageSchema.methods.isApproved = function () {
  return this.moderationStatus === 'Approved';
};

// Method to increment views
imageSchema.methods.incrementViews = function () {
  this.views += 1;
  return this.save();
};

// Method to toggle like
imageSchema.methods.toggleLike = function (userId) {
  const index = this.likedBy.indexOf(userId);
  if (index > -1) {
    this.likedBy.splice(index, 1);
    this.likes = Math.max(0, this.likes - 1);
  } else {
    this.likedBy.push(userId);
    this.likes += 1;
  }
  return this.save();
};

// Static method to get popular images
imageSchema.statics.getPopularImages = function (limit = 12) {
  return this.find({ moderationStatus: 'Approved' })
    .sort({ likes: -1, createdAt: -1 })
    .limit(limit);
};

// Static method to get recently uploaded approved images
imageSchema.statics.getRecentImages = function (limit = 12) {
  return this.find({ moderationStatus: 'Approved' })
    .sort({ createdAt: -1 })
    .limit(limit);
};
export const Image = mongoose.model('Image', imageSchema);
